### PR TITLE
167 341 multiple titles

### PR DESCRIPTION
**Pull request by odscjames**
https://github.com/codeforIATI/iati-datastore/issues/167
https://github.com/codeforIATI/iati-datastore/issues/341

### CODE REVIEW

**Review by markbrough — COMMENTED** [review]
Would it not be better to have all the titles in a separate table, rather than JSONB, in order to be consistent with the rest of the model?

**Comment by odscjames** [comment]
So something like:

```
class ActivityTitle(db.Model):
    __tablename__ = "title"
    id = sa.Column(
            sa.Integer,
            primary_key=True)
    activity_id = sa.Column(
            act_ForeignKey("activity.iati_identifier"),
            nullable=False,
            index=True)
    lang = sa.Column(sa.Unicode, nullable=True)
    title = sa.Column(sa.Unicode, nullable=False)
    # unique constraint on (activity_id, lang)

# same for description but also with a type column, also nullable
```

lang could be null for a default title in the data.

That would require an extra join on selecting and that join would get complicated as you'd want to select both lang=WHATEVER and lang=Null. In cases where the first one didn't exist you'd want to fall back to the the other one. Also is it ever likely we'd get into situations where the difference between es & es-BO was important? Then the select may get even more complicated (someone requesting es-BO could be served es or maybe another es_* if es-BO doesn't exist)

Also we'd need to make sure that if a data source removed a language, we also removed the associated table rows otherwise we would be promoting old data - but maybe that's already handled for things like ActivityWebsite, I haven't checked yet.

So I think I went for JSON as I thought it would be better performance and easier to deal with, and I didn't see a need to be able to refer to to an ActivityTitle by it's own ID.

But I'm happy to look at tables if preferred?
  
Also, any comment on how the search should work?

**Comment by odscjames** [comment]
Meeting today - we'll leave as columns.

Make search work would be ideal - it's ok to search across all languages for now. ie ignore the locale the user sets.

**Review by markbrough — APPROVED** [review]
This looks great to me! Thank you!!

**Review by markbrough — COMMENTED** [review]
Would it also make sense to update the search functions here? I think so?

https://github.com/codeforIATI/iati-datastore/blob/729e58c4339c573ad26850c1d086ce783c8bd3e8/iati_datastore/iatilib/frontend/dsfilter.py#L222-L226

**Comment by odscjames** [comment]
> Would it also make sense to update the search functions here? I think so?

We should do this as part of this P.R. - I'm realising that to make that search easier we may change the storage a bit

**Comment by odscjames** [comment]
Need to look at WIP commit, and also add back work that uses correct titles in CSV's:

```


--- a/iati_datastore/iatilib/frontend/serialize/csv.py
+++ b/iati_datastore/iatilib/frontend/serialize/csv.py
@@ -8,7 +8,7 @@ from iatilib import codelists
 from pyexcelerate import Workbook
 from openpyxl_copy.utils import get_column_letter
 from flask_babel import gettext
-
+from flask import request
 
 def total(column):
     def accessor(activity):
@@ -122,7 +122,17 @@ def transaction_org(field, transaction):
 provider_org = partial(transaction_org, 'provider_org')
 receiver_org = partial(transaction_org, 'receiver_org')
 
-title = attrgetter("title")
+
+def title(activity):
+    locale = request.args.get("locale", "en")
+    if activity.title_all_values and locale in activity.title_all_values:
+        return activity.title_all_values[locale]
+    elif activity.title_all_values and 'default' in activity.title_all_values:
+        return activity.title_all_values['default']
+    else:
+        return activity.title
+
+


```

**Comment by odscjames** [comment]
Close, #370 instead

**Pull request closed without merging**
