### PR TITLE
Fix budget type bug, fixes #259

### LINKED ISSUE #259: Budget type can be None
### Describe the bug

When trying to download the following file, an empty CSV file is returned:

https://datastore.codeforiati.org/api/1/access/budget/by_sector.csv?reporting-org=GB-GOV-1&stream=True

In the logs, the following error is captured:
```
Traceback (most recent call last):
  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/werkzeug/wsgi.py", line 506, in __next__
    return self._next()
  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/flask/helpers.py", line 162, in generator
    for item in gen:
  File "/home/admin/iati-datastore/iati_datastore/iatilib/frontend/serialize/csv.py", line 415, in __call__
    row = [accessor(obj) for accessor in self.fields_by_major_version[get_major_version(obj)].values()]
  File "/home/admin/iati-datastore/iati_datastore/iatilib/frontend/serialize/csv.py", line 415, in <listcomp>
    row = [accessor(obj) for accessor in self.fields_by_major_version[get_major_version(obj)].values()]
  File "/home/admin/iati-datastore/iati_datastore/iatilib/frontend/serialize/csv.py", line 705, in wrapper
    return func(t)
  File "/home/admin/iati-datastore/iati_datastore/iatilib/frontend/serialize/csv.py", line 240, in budget_type
    return budget.type.name
AttributeError: 'NoneType' object has no attribute 'name'
```

### To Reproduce

1. Go to the above URL
2. See the eerror

### Expected behaviour

Output should contain all activity-budget-sector rows.

### PR DESCRIPTION
**Pull request by markbrough**
Budget type can sometimes be None. In this case, it will have no Name.

### CODE REVIEW

**Comment by andylolz** [comment]
I wonder if it’s preferable to follow a style used elsewhere in the serializer, e.g.:

```python
def budget_type(budget):
    try:
        return budget.type.name
    except AttributeError:
        return ""
```

**Comment by markbrough** [comment]
I tried this and interestingly, `None`s are output as empty strings:

https://github.com/codeforIATI/iati-datastore/pull/260/commits/03039569aa0323b53abc5d8a82a575894361f65e#diff-bde992c43f4345847f3a67cad51b1d90bbc926495235e1a210772f94ae7915d2R292

**Comment by markbrough** [comment]
On second thoughts, I think it's good for the code to be consistent, so I have adjusted this as suggested.

**Review by andylolz — APPROVED** [review]
Nice – this looks great

**Pull request merged**
