### PR TITLE
Set User-Agent header

### LINKED ISSUE #84: Consider setting the User-Agent to ‘IATI datastore’ or similar
I.e. just here:
https://github.com/IATI/IATI-Datastore/blob/5b871aa3/iati_datastore/iatilib/crawler.py#L163

At least one publisher [blocks requests with a `User-Agent` containing ‘python-requests’](https://gist.github.com/andylolz/dd6cb83316670ea94a21876dcd219ae7) (!) But regardless of that, it’s useful for publishers to have their own record of when their data is being harvested by the datastore & other IATI tools etc.

### PR DESCRIPTION
**Pull request by andylolz**
Fixes #84.

### CODE REVIEW

**Comment by markbrough** [comment]
I think this is a good idea, but it made me think -- IIRC some servers behave strangely when a User-Agent header is set. I think we should just have a better way of easily identifying / displaying those kind of download errors in general. It would be really nice to have a simple user interface that tells you when a file was last updated and/or lists files with errors.

**Comment by andylolz** [comment]
> It would be really nice to have a simple user interface that tells you when a file was last updated and/or lists files with errors. Obviously this data is already captured in the database so should be pretty straightforward to display it.

^^ Totally agree – this would be great!

**Comment by markbrough** [comment]
Should we merge this as is?

**Comment by andylolz** [comment]
I’ve force-pushed to add the word “classic” to the end.

> should we merge this as is?

I don’t mind really. I think it’s probably fine to merge it as is, and create a new issue about identifying and displaying download errors.

**Comment by markbrough** [comment]
Agreed, let's merge!

**Pull request merged**
