### PR TITLE
Cache currency conversion table for performance reasons

### PR DESCRIPTION
**Pull request by radix0000**
Includes cache key with date added, both to make tests work (using different key as data is different) and so cache expires after 24 hours

### CODE REVIEW

**Comment by markbrough** [comment]
Hey @radix0000 I am a bit unsure about the merits of having a global variable floating around, but maybe @andylolz can weigh in on this.

Would another option be to just load the exchange rates data from disk at the start of `parse_resource()`, i.e. once for each item on the queue?
https://github.com/codeforIATI/iati-datastore/blob/main/iati_datastore/iatilib/crawler.py#L187

I guess you would have to pass that data quite a long way down through various functions, but it still feels a bit cleaner and simpler than this approach?

I just tested on my local machine and loading all the `imf_exchangerates.csv` data this way:
````
converter = exchangerates.CurrencyConverter(update=False, source='imf_exchangerates.csv')
```
... takes 0.32 seconds (probably that library could be sped up even more)

**Comment by radix0000** [comment]
Hi @markbrough Happy to cache the data in parse_resource() and pass it around if you want. I guess a compromise would be to split the caching code out into its own file, use a closure to keep data out of the global namespace and modify the crawler code to call a function to delete the cache at end of task. But would be functionally pretty equivalent, though would avoid having to make changes to every function the cache object would have to be passed through. Anyway let me know, can do either.

**Comment by markbrough** [comment]
OK I will leave it up to you which approach you think is better.

In any case -- how about we just go ahead with this for now and then we can adjust it later if necessary? I think this is a big improvement in the speed of processing already, so would be good to get it deployed.

**Review by markbrough — APPROVED** [review]
Looks good to me, thanks @radix0000

**Pull request merged**
