### PR TITLE
Decrease non-streaming query limit to 1000

### LINKED ISSUE #58: Add query limit to non-streaming mode
Otherwise users can use arbitrary amounts of RAM on the server.

### PR DESCRIPTION
**Pull request by andylolz**
Fixes #58.

This is maybe a bit controversial, so have a look at #58 and #29, and let me know if you’re happy with it!

### CODE REVIEW

**Comment by andylolz** [comment]
I think with #220 and #221, this PR isn’t really necessary. Closing.

**Comment by andylolz** [comment]
Reopening this, because although I don’t think it’s necessary, I think it’s probably still good to put a reasonable hard limit on page size.

**Comment by markbrough** [comment]
I agree, looks good to me! I just added some small tweaks to the documentation to make clear 1000 is now a hard limit without streaming.

**Comment by andylolz** [comment]
Nice – thank you!

**Pull request merged**
