### PR TITLE
Output converted currency columns (USD + EUR)

### PR DESCRIPTION
**Pull request by radix0000**

### CODE REVIEW

**Comment by markbrough** [comment]
Fixes #335 #378

**Comment by markbrough** [comment]
@radix0000 Should we merge this?

**Comment by markbrough** [comment]
This looks good! Is it ready to go @radix0000 ?

**Comment by radix0000** [comment]
Found one more issue in testing, negative values. They aren't currently being converted. Are they valid (in context of transactions and budgets), and should they be treated like 0.0 values and converted? If so, is quick fix and can merge asap.

**Comment by markbrough** [comment]
Negative values are valid. Can they not just be converted to the correct amount in USD/EUR by multiplying against the exchange rate?

e.g. if GBP 100 = USD 116.55314 (as at present, according to xe.com), then:
GBP -100 = USD -116.55314

**Review by markbrough — APPROVED** [review]

**Pull request merged**
