### PR TITLE
CSV download: Eager load joined tables

### PR DESCRIPTION
**Pull request by odscjames**
Performance boost to /api/1/access/activity.csv

### CODE REVIEW

**Comment by odscjames** [comment]
Load testing is showing a small improvement. However Hetzner is currently having network issues so I need to wait and redo them later.

Also seeing an odd issue where the results are different. Need to check that again.

**Comment by odscjames** [comment]
> Load testing is showing a small improvement. However Hetzner is currently having network issues so I need to wait and redo them later.

Hetzner network troubles are now over

A CSV of all Indias activity - /api/1/access/activity.csv?recipient-country=IN&stream=True on the dev server (real data) is 80% the speed it used to be.

* First request (so no cache) 80S to 64S
* Subsequent requests (postgres cache will probably be helping) 79S to 63S 

> Also seeing an odd issue where the results are different. Need to check that again.

diff of the 2 files is exactly the same.

So not sure  what that issue was last week - Hetzner's network problems dropping a connection half way through a download? If you look at code diff there is no reason contents should change

**Comment by odscjames** [comment]
Reran checks whilst watching node_memory_MemAvailable_bytes on server monitoring - no signifiant changes seen

Because the ORM works through activities in batches I expected this.

**Review by andylolz — APPROVED** [review]
Looks good!

**Pull request merged**
