### PR TITLE
Don’t raise IndexErrors during crawl

### LINKED ISSUE #166: update_dataset raises an IndexError for some datasets
```
  File "iati_datastore/iatilib/crawler.py", line 284, in update_dataset
    resource = fetch_resource(dataset.resources[0])
IndexError: list index out of range
```

### PR DESCRIPTION
**Pull request by andylolz**
Fixes #166.

### CODE REVIEW

**Comment by markbrough** [comment]
I think this means: if there is an integrity error (because any resource of a dataset shares the URL of an existing resource), then we should not add that dataset. Before, we would just not add the resource. Is that correct?

**Comment by andylolz** [comment]
Good question. I think if you call:
```
iati crawler download-and-update
```
…the following things happen:
 1. A snapshot of data is fetched from IATI data dump
 2. `fetch_dataset_list` runs, which a) adds lots of new, unpopulated dataset objects to the database, and b) deletes removed datasets and their corresponding activities
 3. Then for each dataset, `update_dataset` is called
 4. This first calls `fetch_dataset_metadata` to hydrate the dataset objects with metadata (including the dataset source URL).
 5. If that’s successful, `fetch_resource` adds the latest XML to the dataset object.
 6. If `fetch_resource` decides the data needs reparsing, `update_activities` actually parses the XML and adds activities

The new bit here is that after 4, if there was a problem saving (e.g. because the dataset source URL already appears elsewhere) we bail.

The unpopulated datasets don’t get deleted, they just don’t get populated. So e.g. here is a populated one:
 * https://datastore.codeforiati.org/api/1/about/dataset/cibe-01/

And here are two unpopulated ones:
 * https://datastore.codeforiati.org/api/1/about/dataset/cibe-test3/
 * https://datastore.codeforiati.org/api/1/about/dataset/cibe-mijndataset/

I guess we could delete these unpopulated datasets, or log errors against them? It’s a bit weird that no error appears here:
 * https://datastore.codeforiati.org/api/1/error/dataset/cibe-test3/
 * https://datastore.codeforiati.org/api/1/error/dataset/cibe-mijndataset/

**Comment by markbrough** [comment]
Thanks a lot for the explanation! I agree it would be good to have some error logs here, and pushed a commit implementing this. Feel free to adjust!!

**Comment by andylolz** [comment]
Nice! Test added (to confirm this works) and I’ve merged.

**Pull request merged**
